### ISSUE TITLE
[Bug] Middle click weirdness

### ISSUE THREAD

**Issue by SnowShock35** [RebelKeithy/DualHotbar#1]
Hi Keithy,

I believe I have found a bug with DualHotbar.
DualHotbar Version: 1.6
Forge: 1208
Description: When middle clicking in creative on a block that goes into one of the dualhotbar slots when placed will vanish (I believe a sync issue).

Hope this helps.
-Snow

**Comment by RebelKeithy** [comment]
This should be fixed in the latest update.

**Comment by SnowShock35** [comment]
Thanks @RebelKeithy even if it only took two years 😛
