### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KristjanKr** [RebelKeithy/DualHotbar#3]
Game crashes with following crash log:

http://paste.ee/p/92G5b

Minecraft: 1.10.2
Forge: 1.10.2-12.18.3.2185
DualHotbar: dualhotbar-1.1x-1.7.1.jar

**Comment by RebelKeithy** [comment]
Hmm, I'm not getting a crash on my 1.10.2 game. Could you post the content of your fml-client-latest.log and latest.log?

**Comment by RebelKeithy** [comment]
I've uploaded an update to curseforge. Let me know if that fixes it.

**Comment by KristjanKr** [comment]
It did fix it indeed.
