### ISSUE TITLE
Crash upon opening world

### ISSUE THREAD

**Issue by ghost** [RebelKeithy/DualHotbar#4]
http://pastebin.com/NChLwkTq

As stated on the title, this happens when any world is opened with the 1.7.1 version of the mod, using the recommended forge version for 1.10.2

**Comment by RebelKeithy** [comment]
Hmm, I'm not getting a crash on my 1.10.2 game. Could you post the content of your fml-client-latest.log and latest.log?

**Comment by RebelKeithy** [comment]
I've uploaded an update to curseforge. Let me know if that fixes it.

**Comment by ghost** [comment]
Just got home and saw the update. It works, Thank you.
